name: cc-beacon

networks:
  traefik-public:
    external: true

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      - ../shared/env/secrets.env
    volumes:
      - ../shared/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ../shared/www:/var/www/cc-beacon:ro
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.cc-beacon.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cc-beacon.entrypoints=websecure"
      - "traefik.http.routers.cc-beacon.tls=true"
      - "traefik.http.routers.cc-beacon.tls.certresolver=letsencrypt"
      - "traefik.http.services.cc-beacon.loadbalancer.server.port=80"
