name: cc-beacon

networks:
  traefik-public:
    external: true

services:
  api:
    image: ghcr.io/marvinlerouge/cc-beacon-api:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - ../shared/env/secrets.env
    volumes:
      - ../shared/data:/data
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.cc-beacon.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cc-beacon.entrypoints=websecure"
      - "traefik.http.routers.cc-beacon.tls=true"
      - "traefik.http.routers.cc-beacon.tls.certresolver=letsencrypt"
      - "traefik.http.services.cc-beacon.loadbalancer.server.port=8000"
